### PR TITLE
feat(ntp): adds tv 2 ntp server

### PR DESCRIPTION
**Pull request by jesperstarkar**

### CODE REVIEW

**Comment by olzzon** [comment]
I think the address should be in the set-environment_EXAMPLE.sh' file.

**Comment by olzzon** [comment]
I think the ntp address should be set in:
```
set-environment_EXAMPLE.sh
```
Instead of hardcoded

**Comment by jesperstarkar** [comment]
Sounds good. Care to refactor?

**Comment by olzzon** [comment]
I´ll do that after merge 👍

**Pull request merged**
